### ISSUE TITLE
Document the tradeoff

### ISSUE THREAD

**Issue by oliviertassinari** [HenriBeck/react-get-not-declared-props#7]
I think that it would be great to document the tradeoff taken by this module in the README.
I will give my vision on it, but it might not align with yours.

The pros:
- It's improving the DX. You do no longer have to duplicate the properties twice in the component. One time for the propTypes and a second time for the render method when destructuring. It's less room for mistakes.

The cons:
- It's decreasing the UX. You need to keep the propTypes in production. You can no longer remove them from the bundle. The bundle will be slightly larger.

**Comment by HenriBeck** [comment]
Totally agree with you on both points.

I've been thinking of writing a small babel plugin which would remove the propTypes in production and replace them with an array to still get the not declared props. This way it would improve the file size and still get the benefits.

**Comment by HenriBeck** [comment]
Added the tradeoffs in #8 and the babel plugin will be tracked in #9

**Comment by oliviertassinari** [comment]
👌
